# Generated by Django 4.2.3 on 2023-07-25 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_invitecard_expiration_date_additionalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecard',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 24, 20, 25, 39, 773528), verbose_name='дата истечения'),
        ),
    ]
